[cronet_http] Upgrade jni to 0.9.2 and publish 1.2.1
dart-lang/http pull request #1198
Opened 2024-05-14 08:01 UTC by HosseinYousefi

Publishing a new version to fix our users' issue described here: https://github.com/dart-lang/native/issues/1119.

2024-05-14 15:20 UTC, brianquinlan requested changes
The tests timed-out so I restarted them. I have one more Dart 3.4-releated change to land and then I will publish this.

2024-05-14 15:20 UTC, brianquinlan commented on pkgs/cronet_http/CHANGELOG.md
> +## 1.2.1
Please change this to "1.2.1-wip"

2024-05-14 15:20 UTC, brianquinlan commented on pkgs/cronet_http/pubspec.yaml
> +version: 1.2.1
Please change this to "1.2.1-wip"

2024-05-14 16:45 UTC, brianquinlan commented
The emulator isn't even starting before the tests time out. Hopefully this is a temporary github glitch.

2024-05-14 19:18 UTC, techouse commented
This happens with AGP 8.4.0. Works fine with AGP 8.3.2

2024-05-15 07:48 UTC, techouse commented
Not on the app level. It has most likely something to do with the jni plugin.

2024-05-15 17:05 UTC, brianquinlan commented
I think that the CI is broken. Working on fixing it.

2024-05-16 00:30 UTC, brianquinlan approved these changes

2024-05-16 08:55 UTC, HosseinYousefi commented
> Not on the app level. My
> 
> ```groovy
> android.defaultConfig.minSdkVersion 24
> ```
> 
> still fails with the same error.
> 
> It has most likely something to do with the jni plugin.

I meant after the fix to jni. You can override the jni dependency to use 0.9.2 and try.

2024-05-16 08:55 UTC, HosseinYousefi commented
> I think that the CI is broken. Working on fixing it.

Thanks! Merge this whenever you see fit then.

2024-05-16 10:16 UTC, techouse commented
> I meant after the fix to jni. You can override the jni dependency to use 0.9.2 and try.

You mean just use this PR instead of `v1.2.0`? Sure, gimme a few minutes.

2024-05-16 10:19 UTC, HosseinYousefi commented
> > I meant after the fix to jni. You can override the jni dependency to use 0.9.2 and try.
> 
> You mean just use this PR instead of `v1.2.0`? Sure, gimme a few minutes.

Yeah, you can do that too, 

Here's the dependency!
```yaml
cronet_http:
  git:
    url: https://github.com/dart-lang/http
    ref: jni-0.9.2
    path: pkgs/cronet_http
```

2024-05-16 10:24 UTC, techouse commented
Yep, compiles ok using

```yaml
dependency_overrides:
  cronet_http:
    git:
      url: https://github.com/dart-lang/http.git
      ref: jni-0.9.2
      path: pkgs/cronet_http
```

and `android/app/build.gradle`

```groovy
dependencies {
  implementation(platform("org.jetbrains.kotlin:kotlin-bom:1.9.24"))
}
```

It only complains about
```
/Users/techouse/.pub-cache/hosted/pub.dev/jni-0.9.2/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java uses or overrides a deprecated API.
```

2024-05-16 10:27 UTC, HosseinYousefi commented
> It only complains about
> 
> ```
> /Users/techouse/.pub-cache/hosted/pub.dev/jni-0.9.2/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java uses or overrides a deprecated API.
> ```

Yeah, that's not a problem. Although, I thought I have silenced this warning here: https://github.com/dart-lang/native/blob/main/pkgs/jni/android/src/main/java/com/github/dart_lang/jni/JniPlugin.java#L22 🤔

2024-05-16 20:58 UTC, merged