🔧 Apply relevant rules with the ProGuard
dart-lang/http pull request #1204
Opened 2024-05-18 14:54 UTC by AlexV525

Resolves #1179

---

- [x] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/wiki/External-Package-Maintenance#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2024-05-19 01:31 UTC, AlexV525 commented
The failing test looks unrelated. https://github.com/dart-lang/http/actions/runs/9140740181/job/25134408655?pr=1204

2024-05-23 23:50 UTC, brianquinlan requested changes

2024-05-23 23:50 UTC, brianquinlan commented on pkgs/cronet_http/CHANGELOG.md
> +## 1.2.2-wip
Could you change this to 1.3.1-wip?

2024-05-23 23:50 UTC, brianquinlan commented on pkgs/cronet_http/pubspec.yaml
> +version: 1.2.2-wip
1.3.1-wip

2024-05-24 02:20 UTC, brianquinlan commented
Thanks @AlexV525 !

2024-05-24 02:24 UTC, brianquinlan approved these changes

2024-05-24 02:24 UTC, merged