Fix "unintended_html_in_doc_comment" analysis errors
dart-lang/http pull request #1291
Opened 2024-08-09 00:02 UTC by brianquinlan

- Thanks for your contribution! Please replace this text with a description of what this PR is changing or adding and why, list any relevant issues, and review the contribution guidelines below.

---

- [ ] I’ve reviewed the contributor guide and applied the relevant portions to this PR.

<details>
  <summary>Contribution guidelines:</summary><br>

- See our [contributor guide](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md) for general expectations for PRs.
- Larger or significant changes should be discussed in an issue before creating a PR.
- Contributions to our repos should follow the [Dart style guide](https://dart.dev/guides/language/effective-dart) and use `dart format`.
- Most changes should add an entry to the changelog and may need to [rev the pubspec package version](https://github.com/dart-lang/sdk/blob/main/docs/External-Package-Maintenance.md#making-a-change).
- Changes to packages require [corresponding tests](https://github.com/dart-lang/.github/blob/main/CONTRIBUTING.md#Testing).

Note that many Dart repos have a weekly cadence for reviewing PRs - please allow for some latency before initial review feedback.
</details>

2024-08-09 14:53 UTC, Anikate-De requested changes

2024-08-09 14:53 UTC, Anikate-De commented on pkgs/http/lib/src/base_response.dart
> +/// start a new `<cookie-pair>` then be part of `<path-value>` or
```suggestion
/// start a new `<cookie-pair>` than be part of `<path-value>` or
```

2024-08-09 14:53 UTC, Anikate-De commented on pkgs/http_profile/lib/src/utils.dart
> +/// Splits comma-seperated "Set-Cookie" header values.
nit:
```suggestion
/// Splits comma-separated "Set-Cookie" header values.
```

2024-08-09 14:53 UTC, Anikate-De commented on pkgs/http_profile/lib/src/utils.dart
> +/// start a new `<cookie-pair>` then be part of `<path-value>` or
nit:
```suggestion
/// start a new `<cookie-pair>` than be part of `<path-value>` or
```

2024-08-09 15:27 UTC, Anikate-De approved these changes

2024-08-13 17:58 UTC, natebosch commented
@devoncarew This PR highlights a false positive for the lint. It doesn't understand square braces well enough and it looks like it flags `[List<int>]`. I think the change to ``` `List<int>` ``` is an improvement, but only slight compared to the obvious improvement from broken HTML. I didn't click on any of these cases when I skimmed the internal results, and the rollout is more churn than I expected.

I also forgot about the unpublished packages where they're unlikely to be noticed since we don't have any workflow where they are visible to users. I don't know whether any IDEs try to render the dartdoc to html for display, but that's the only use case I can imagine is affected.

2024-08-13 18:03 UTC, natebosch approved these changes
http and http_profile can both be bumped to the next version with `-wip`.

2024-08-13 18:26 UTC, devoncarew commented
> @devoncarew This PR highlights a false positive for the lint. It doesn't understand square braces well enough and it looks like it flags `[List<int>]`. I think the change to `` `List<int>` `` is an improvement, but only slight compared to the obvious improvement from broken HTML. I didn't click on any of these cases when I skimmed the internal results, and the rollout is more churn than I expected.

Gotcha; can you file an issue in the sdk for this? We have had some other recent false positives (https://github.com/dart-lang/sdk/issues/56450) addressed - now fixed in head.

2024-08-13 21:05 UTC, natebosch commented
https://github.com/dart-lang/sdk/issues/56465

2024-08-13 21:39 UTC, brianquinlan commented
> http and http_profile can both be bumped to the next version with `-wip`.

Done

2024-08-13 22:02 UTC, natebosch approved these changes

2024-08-13 22:14 UTC, merged