Fix Default Encoding for application/json Content-Type in HTTP Responses
dart-lang/http pull request #1422
Opened 2024-12-12 14:09 UTC by snoopdoggy322

This merge request addresses a long-standing issue (https://github.com/dart-lang/http/issues/175) where the http package defaults to latin1 encoding when no charset is specified in the Content-Type header. Per [RFC 8259](https://www.rfc-editor.org/rfc/rfc8259), the default encoding for application/json should be utf-8.

The fix ensures that responses with Content-Type: application/json and no explicit charset parameter are decoded using utf8 by default. This change improves compliance with the JSON standard and prevents decoding errors for valid JSON payloads encoded in utf-8.

2025-01-14 09:54 UTC, snoopdoggy322 commented
can anyone reply to my pull request?

2025-02-04 00:23 UTC, seifibrahim32 commented
It is fine but, could you try to pass some Chinese or Korean language tests through conformance tests? @snoopdoggy322

2025-02-04 04:18 UTC, kevmoo commented
CC @brianquinlan @devoncarew 

Ooo...could be good

2025-02-04 16:18 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +  /// [RFC3629][].
Could you site a section? Is this only for JSON data for for all payloads?

2025-02-04 17:28 UTC, snoopdoggy322 commented on pkgs/http/lib/src/response.dart
> +  /// [RFC3629][].
Yes, RFC7231 requires interpreting application/json as UTF-8, everything else is described as incorrect interpretation of the specification

2025-02-04 17:53 UTC, brianquinlan reviewed
Excellent work, we are almost there!

Would you also:
1. change the version in pubspec.yaml to version: 1.4.0-wip
2. add a 1.4.0-wip section to CHANGELOG.md with a description of your change

2025-02-04 17:53 UTC, brianquinlan commented on pkgs/http/test/response_test.dart
> +      expect(response.body, equals('{"foo":"Привет, мир!"}'));
Ideally, there should be one `except` per test because you are testing a single scenario.

Could you add tests for these additional scenarios:
1. test `.body` with a non-empty charset with content-type application/json data (e.g. with Russian and iso-8859-1)
2. test `.body` with an empty charset with a content-type of test/plain (e.g. with Russian to verify that the default of iso-8859-1 is used)

2025-02-04 17:53 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +/// - Defaults to [utf8] if the `Content-Type` is `application/json` (since JSON is defined to use UTF-8 by default).
Wrap to 80 columns

2025-02-04 17:53 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +  /// encoding name is unknown, [utf8] is used by default,
This is only when content-type is UTF-8 right? So could you clarify that in your comments e.g.

If it's unavailable or if the encoding name is unknown:
1. [utf8] is used when the content-type is `'application/json'` (see [RFC 3629]).
2. [latin1] is used in all other cases (see [RFC 2616][]).

2025-02-05 10:37 UTC, snoopdoggy322 commented on pkgs/http/lib/src/response.dart
> +  /// encoding name is unknown, [utf8] is used by default,
@brianquinlan, thanks for the review.
Let me know if anything else needs improvement! 🚀

2025-02-05 18:34 UTC, brianquinlan requested changes
Could you update from master so I can run the CI?

2025-02-05 18:34 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +  /// - [utf8] is used when the content-type is 'application/json' (see [RFC 3629]).
```suggestion
  /// - [utf8] is used when the content-type is 'application/json' (see [RFC 3629][]).
```

2025-02-05 18:34 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +  /// [RFC 3629]:https://www.rfc-editor.org/rfc/rfc3629.
```suggestion
  /// [RFC 3629]: https://www.rfc-editor.org/rfc/rfc3629.
```

2025-02-07 01:12 UTC, brianquinlan commented on pkgs/http/lib/src/response.dart
> +  /// encoding name is unknown, [utf8] is used by default,
I think that this is great! Thank you so much for your contribution!

2025-02-07 01:13 UTC, brianquinlan approved these changes

2025-02-07 01:13 UTC, merged